name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - 'release/v*.*.*'

jobs:
  build_and_upload_release_assets:
    name: Build and upload binary assets
    strategy:
      fail-fast: false
      matrix:
        settings:
          - platform: macos-latest
            target: aarch64-apple-darwin                      # Apple Silicon
            asset_name: vim-doge-helper-macos-aarch64
            asset_path: ./bin/vim-doge-helper-macos-aarch64.tar.gz

    runs-on: ${{ matrix.settings.platform }}
    steps:
      - name: Checkout kkoomen/vim-doge
        uses: actions/checkout@v3

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin, x86_64-apple-darwin, aarch64-unknown-linux-gnu

      - name: Install Cargo dependencies (linux)
        if: runner.os == 'Linux'
        run: cargo install cross
        shell: bash

      - name: Build (unix)
        if: runner.os != 'Windows'
        run: ./scripts/build.sh "${{ matrix.settings.target }}" "${{ matrix.settings.asset_name }}"
        shell: bash

      - name: Build (windows)
        if: runner.os == 'Windows'
        run: ./scripts/build.ps1 "${{ matrix.settings.target }}" "${{ matrix.settings.asset_name }}"

      - name: Get current app version
        id: tag_name
        run: echo "version=$(cat .version)" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: v${{ steps.tag_name.outputs.version }}
          files: ${{ matrix.settings.asset_path }}
          draft: false
          prerelease: false
